name: ucabdemy
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #STATE
  provider: ^5.0.0
  path_provider: ^2.0.10

  #DATA
  shared_preferences: ^2.0.13
  http: ^0.13.4
  #webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.0.9

  #IMAGE
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  video_player: ^2.4.4
  flutter_launcher_icons:

  #JITSI
  jitsi_meet: ^4.0.0

  #FIREBASE
  firebase_core: ^1.19.2
  firebase_storage: ^10.3.2
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.0

  #UTILS
  fluttertoast: ^8.0.7
  avatar_glow: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo_app.png"
  adaptive_icon_background: "assets/image/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/